# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ashish Bista
email: poisonta03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Developer by Profession, Passion & Obsession;
  Hello, my name is Ashish Bista. This is my technical blog.
  I'm into both Rails & DevOps. However, I believe in the potential of technology, not in tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ashishbista.com" # the base hostname & protocol for your site
twitter_username: poisonta03
github_username:  ashishbista

# Build settings
markdown: kramdown
